"""add_query_indexes_to_trips_and_itineraries

Revision ID: 4731315f30d1
Revises: 4573db112fb8
Create Date: 2024-11-14 15:40:35.389361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4731315f30d1'
down_revision: Union[str, None] = '4573db112fb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
