"""add_published_and_favorite_to_trips

Revision ID: 4e0953d66662
Revises: 5f44fd20a19c
Create Date: 2024-11-08 10:43:25.490672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e0953d66662'
down_revision: Union[str, None] = '5f44fd20a19c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
