"""add_optional_trip_fields

Revision ID: 51a0bf097baa
Revises: 7e29a7884522
Create Date: 2024-11-06 12:35:00.211741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '51a0bf097baa'
down_revision: Union[str, None] = '7e29a7884522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itineraries', sa.Column('lunch_suggestions', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('itineraries', sa.Column('dinner_suggestions', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('itineraries', sa.Column('ai_suggestions', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('itineraries', 'morning_activities',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('itineraries', 'afternoon_activities',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('trips', sa.Column('arrival_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('trips', sa.Column('departure_time', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('trips', sa.Column('dietary_preferences', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('trips', sa.Column('activity_preferences', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('trips', sa.Column('additional_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_trips_user_id'), 'trips', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_user_id'), table_name='trips')
    op.drop_column('trips', 'additional_notes')
    op.drop_column('trips', 'activity_preferences')
    op.drop_column('trips', 'dietary_preferences')
    op.drop_column('trips', 'departure_time')
    op.drop_column('trips', 'arrival_time')
    op.alter_column('itineraries', 'afternoon_activities',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('itineraries', 'morning_activities',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('itineraries', 'ai_suggestions')
    op.drop_column('itineraries', 'dinner_suggestions')
    op.drop_column('itineraries', 'lunch_suggestions')
    # ### end Alembic commands ###
