"""fix_budget_preference_enum

Revision ID: 5f44fd20a19c
Revises: ce6e653356ec
Create Date: 2024-11-07 20:57:51.609385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f44fd20a19c'
down_revision: Union[str, None] = 'ce6e653356ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
