"""add_user_profiles

Revision ID: 7976d6d17eff
Revises: 51a0bf097baa
Create Date: 2024-11-07 12:21:03.799089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7976d6d17eff'
down_revision: Union[str, None] = '51a0bf097baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('traveler_type', sa.Enum('SOLO', 'COUPLE', 'FAMILY', 'GROUP', name='travelertype'), nullable=True),
    sa.Column('activity_level', sa.Enum('RELAXED', 'MODERATE', 'ACTIVE', name='activitylevel'), nullable=True),
    sa.Column('special_interests', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dietary_preferences', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('accessibility_needs', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_languages', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('budget_preference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
