"""create_structured_itinerary_tables

Revision ID: d6c96471c840
Revises: e9a49ed21d63
Create Date: 2024-11-09 00:06:34.678538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6c96471c840'
down_revision: Union[str, None] = 'e9a49ed21d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_itineraries_id', table_name='itineraries')
    op.drop_table('itineraries')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itineraries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('day_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('morning_activities', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('afternoon_activities', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('evening_activities', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lunch_suggestions', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('dinner_suggestions', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ai_suggestions', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name='itineraries_trip_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='itineraries_pkey')
    )
    op.create_index('ix_itineraries_id', 'itineraries', ['id'], unique=False)
    # ### end Alembic commands ###
