"""add_travel_tips_to_itineraries

Revision ID: e7473b2014b7
Revises: f9ab965b3120
Create Date: 2024-11-16 14:03:19.501522
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7473b2014b7'
down_revision: Union[str, None] = 'f9ab965b3120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itineraries', sa.Column('travel_tips', postgresql.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itineraries', 'travel_tips')
    # ### end Alembic commands ###