"""add_published_and_favorite_columns

Revision ID: e9a49ed21d63
Revises: 4e0953d66662
Create Date: 2024-11-08 14:48:57.983470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9a49ed21d63'
down_revision: Union[str, None] = '4e0953d66662'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('is_published', sa.Boolean(), nullable=False))
    op.add_column('trips', sa.Column('is_favorite', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'is_favorite')
    op.drop_column('trips', 'is_published')
    # ### end Alembic commands ###
