"""Added_second_and_third_hotels_to_accomodation

Revision ID: f9ab965b3120
Revises: 5a67f249582d
Create Date: 2024-11-15 12:24:29.425320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ab965b3120'
down_revision: Union[str, None] = '5a67f249582d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itineraries', sa.Column('accommodation', sa.JSON(), nullable=True))
    op.drop_column('itineraries', 'hotel_description')
    op.drop_column('itineraries', 'hotel_location')
    op.drop_column('itineraries', 'hotel_name')
    op.drop_column('itineraries', 'hotel_rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itineraries', sa.Column('hotel_rating', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('itineraries', sa.Column('hotel_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('itineraries', sa.Column('hotel_location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('itineraries', sa.Column('hotel_description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('itineraries', 'accommodation')
    # ### end Alembic commands ###
